# Generated by Django 2.1.7 on 2019-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(help_text='삭제 일시', null=True)),
                ('name', models.CharField(help_text='이름', max_length=128)),
                ('price', models.IntegerField(default=0, help_text='가격')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
