# Generated by Django 2.1.7 on 2019-03-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpos_account', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
    ]
