# Generated by Django 2.1.7 on 2019-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpos_account', '0003_auto_20190331_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='value',
            field=models.CharField(max_length=43),
        ),
    ]
